const mongoose = require('mongoose');

const BlogSettingsSchema = new mongoose.Schema(
  {
    singletonKey: { type: String, default: 'ai-blog-settings', unique: true },
    autoPublishEnabled: {
      type: Boolean,
      default: process.env.BLOG_AUTO_PUBLISH_ENABLED === 'true',
    },
    publishingTime: { type: String, default: process.env.BLOG_CRON_TIME || '09:00' },
    timezone: { type: String, default: process.env.BLOG_TIMEZONE || 'Europe/Berlin' },
    articlesPerDay: { type: Number, default: 1, min: 1, max: 10 },
    maxArticlesPerDay: { type: Number, default: 1, min: 1, max: 10 },
    enabledLanguages: { type: [String], default: ['en', 'ar', 'de'] },
    autoPublish: { type: Boolean, default: true },
    autoPublishMode: {
      type: String,
      enum: ['off', 'draft-only', 'publish-if-safe'],
      default: 'draft-only',
    },
    minimumSeoScore: { type: Number, default: 70, min: 0, max: 100 },
    minimumQualityScore: { type: Number, default: 70, min: 0, max: 100 },
    requireValidSchema: { type: Boolean, default: true },
    requireImageAlt: { type: Boolean, default: true },
    requireFaq: { type: Boolean, default: true },
    requireCta: { type: Boolean, default: true },
    requireNoBrokenInternalLinks: { type: Boolean, default: true },
    requireNoDuplicateSimilarityWarning: { type: Boolean, default: true },
    allowDuplicateDrafts: { type: Boolean, default: false },
    forbiddenTopics: { type: [String], default: [] },
    allowedTopicCategories: {
      type: [String],
      default: [
        'flights',
        'travel',
        'airports',
        'baggage',
        'airline-rules',
        'cheap-flights',
        'family-travel',
        'pet-travel',
        'visa-travel-tips',
        'hotels',
        'car-rental',
        'destinations',
      ],
    },
    trendProvider: { type: String, default: process.env.AI_PROVIDER || 'manual-seeds' },
    trendSeedKeywords: {
      type: [String],
      default: [
        'cheap flights from Germany',
        'Istanbul airport transfer tips',
        'Dubai family travel',
        'baggage rules Europe',
        'Lebanon travel tips',
        'Turkey visa travel guide',
        'airport parking Germany',
        'car rental Europe travel',
      ],
    },
    maxConcurrentAiJobs: { type: Number, default: 1, min: 1, max: 5 },
    maxJobRetries: { type: Number, default: 2, min: 0, max: 5 },
    dailyGenerationLimit: { type: Number, default: 3, min: 0, max: 100 },
    monthlyGenerationLimit: { type: Number, default: 60, min: 0, max: 1000 },
    dailyTokenLimit: { type: Number, default: 120000, min: 0 },
    dailyCostLimit: { type: Number, default: Number(process.env.AI_DAILY_BUDGET_LIMIT || 10), min: 0 },
    monthlyCostLimit: { type: Number, default: Number(process.env.AI_MONTHLY_BUDGET_LIMIT || 200), min: 0 },
    fallbackResearchEnabled: { type: Boolean, default: true },
    semanticSimilarityThreshold: { type: Number, default: 0.9, min: 0, max: 1 },
    publishSimilarityThreshold: { type: Number, default: 0.94, min: 0, max: 1 },
    topicRetryAttempts: { type: Number, default: 5, min: 1, max: 10 },
    maxInternalLinksPerArticle: { type: Number, default: 5, min: 0, max: 20 },
    requireInternalLinks: { type: Boolean, default: true },
    autoApplyCtrOptimizations: { type: Boolean, default: false },
    imageProvider: { type: String, default: process.env.AI_IMAGE_PROVIDER || 'prompt-only' },
    fallbackFeaturedImage: { type: String, default: '/plane.jpg' },
    contentRefreshAfterDays: { type: Number, default: 180, min: 1, max: 2000 },
    flightTrackerEnabled: { type: Boolean, default: true },
    flightTrackerCacheDurationMs: { type: Number, default: 60_000, min: 10_000, max: 300_000 },
    flightTrackerMaxAircraftReturned: { type: Number, default: 75, min: 10, max: 250 },
    flightTrackerDefaultRegion: { type: String, default: 'global' },
    flightTrackerEnabledRegions: {
      type: [String],
      default: ['global', 'germany', 'europe', 'turkey', 'middle-east'],
    },
      flightTrackerShowCta: { type: Boolean, default: true },
      flightTrackerPollingIntervalMs: { type: Number, default: 60_000, min: 30_000, max: 180_000 },
      flightTrackerCommercialProvider: { type: String, default: 'none' },
      scheduledQaEnabled: { type: Boolean, default: false },
    qaScheduleTime: { type: String, default: '08:00' },
    qaFrequency: { type: String, enum: ['daily', 'weekly'], default: 'daily' },
    notifyAdminOnIssues: { type: Boolean, default: true },
    emailNotificationsEnabled: { type: Boolean, default: false },
    whatsappNotificationsEnabled: { type: Boolean, default: false },
    notificationRecipients: { type: [String], default: [] },
    whatsappNotificationRecipients: { type: [String], default: [] },
    notificationSeverityThreshold: {
      type: String,
      enum: ['info', 'warning', 'error'],
      default: 'error',
    },
    notificationQuietHours: {
      enabled: { type: Boolean, default: false },
      start: { type: String, default: '22:00' },
      end: { type: String, default: '07:00' },
    },
    lastQaRunAt: { type: Date, default: null },
    lastQaStatus: { type: String, default: '' },
    lastRunAt: { type: Date, default: null },
    lastRunStatus: { type: String, default: '' },
    lastRunMessage: { type: String, default: '' },
  },
  { timestamps: true }
);

module.exports = mongoose.model('BlogSettings', BlogSettingsSchema);
